(in-package :basic.linear-space)

(let ((matrix (list (iota 5)
                    '(0 0 0 0 0)
                    '(0 0 0 0 0)
                    '(0 0 0 0 0)
                    (iota 5 :start 5)
                    (iota 5 :start 10)
                    (iota 5 :start 15)
                    )))
  #+nil(print-matrix (solve matrix))
  (print-matrix (solve '((0 0 3)
                         (2 1 4)
                         (3 4 67))))
  (print-matrix (solve '((3 4 67)
                         (2 1 4)
                         (0 0 3)))))
